### ISSUE TITLE
Open and closed lectures

### ISSUE THREAD

**Issue by Masce** [tohalla/isla#53] opened 2016-04-26 13:28 UTC
When you open new lecture, the lecture gets the date and timing +3h from opening. Is that the closing time? What if the lecture takes time for 4h? Should opened and closed lectures separate with some icons? For example open lecture would have text "open" after the name, or the closed lecture had a picture of lock after it?

And in faculty view, should the course listing have text "open lectures" for those courses that have an open lecture right now? Would it help finding the open lectures?

**Comment by tohalla** [comment] 2016-04-26 14:26
It should display the opening time. I think the reason behind it is that the custom date time serializer transforms  the given time to utc (e.g. when inputting finlands summertime(utc+3) tries to serialize it to utc+3 again, so the output value would be input time + 3h) 

I'll take a look at this later this week

**Comment by tohalla** [comment] 2016-05-09 18:59
time issue resolved. rest is duplicate of #47

**Closed by tohalla** 2016-05-09 18:59 UTC
