### ISSUE TITLE
Active session listing

### ISSUE THREAD

**Issue by henoja** [tohalla/isla#47] opened 2016-04-17 19:12 UTC
Active session listing in active session feed. Location main page/view. Seach tool included.

**Comment by tohalla** [comment] 2016-05-08 17:20
list active sessions directly or just courses with an active session?

**Comment by henoja** [comment] 2016-05-09 21:57
All active sessions listed. Can be categorized by faculties such as:

Tietotekniikan erikoiskysymyksiä
Ohjelmointi
----
Semantiikka
Englannin kielen historia
----
Markkinoinnin perusteet
Kansainvälinen liiketoiminta
International Business Etiquet
Export operations

Color/font or alternative way to highlight active sessions in different faculties, e.g technlogy blue, business red, philosophy green et al.

**Comment by tohalla** [comment] 2016-05-15 12:58
close as duplicate of #46

**Closed by tohalla** 2016-05-15 12:58 UTC
Labels: feature, user interface
